# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # 6-14-16 learn-rails (find the environment variables in ~/.bash_profile):
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  # Rails default:
  secret_key_base: c12a0b9bbf8731f8f7532a20a69adecfb2311ca924a35d7dc19b1bf352bc1806f016c9795fe5c4521ca334f270dbafe553262947eafe478e75c8dc516839ee65

test:
  secret_key_base: 4ff3fdebcb26f960cd7dfee4eb97c572c227de991d3e9ad8acbbec590bf38b4fca32586ec932a437c9bf5ce1518ae59191f8018f0cc6c9c7b4ada12dc316dadd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # 6-14-16 learn-rails (find the environment variables in ~/.bash_profile):
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  # Rails default:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
